config/routes.rb
Rails.application.routes.draw do

  resources :gossip #ok
  resources :home
  root 'home#index'
  resources :welcome
  resources :contact
  resources :user
  resources :team
  resources :city
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users 
  validates :name, length: { in: 2..200 }, presence: true
  validates :zip_code, length: { in: 2..50 }, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tag_gossip_links
  has_many :tags, through: :tag_gossip_links
  validates :title, length: { in: 6..50 }, presence: true
  validates :content, length: { in: 2..500 }, presence: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_many :recipient_to_pm_links, foreign_key: 'received_message_id'
  has_many :recipients, foreign_key: 'recipient_id', class_name: 'User', through: :recipient_to_pm_links
  validates :content, presence: true
  validates :sender, presence: true
end

app/models/recipient_to_pm_link.rb
class RecipientToPmLink < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :received_message, class_name: "PrivateMessage"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_gossip_links
  has_many :gossips, through: :tag_gossip_links
  validates :title, length: { in: 2..50 }, presence: true
end

app/models/tag_gossip_link.rb
class TagGossipLink < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :recipient_to_pm_links, foreign_key: 'recipient_id'
  has_many :received_messages, foreign_key: 'received_message_id', class_name: "PrivateMessage", through: :recipient_to_pm_links
#  validates :first_name, presence: true, length: { in: 6..100 }
#  validates :last_name, presence: true, length: { in: 6..100 }
#  validates :description, presence: true, length: { in: 2..200 }
  #validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }, , length: { in: 3..300 }
#  validates :age, presence: true, length: { in: 1..3 }
#  validates :city_id, presence: true
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params[:id])
  end

def index
    @city = City.all
end

end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  add_flash_types :success , :danger

  def show
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
    @gossip = Gossip.find(params[:id])
   @user = Gossip.find(params[:id]).user.id
   end

  def new
    # Méthode qui crée un potin vide et l'envoie une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    @gossip = Gossip.new
    @user  = User.new(city_id: 4)

  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    @gossip = Gossip.create(title: params[:title], content: params[:content], user_id: 2)
    @user = User.create(first_name: params[:author_name], city_id: 4)

    if @gossip.valid?
      redirect_to '/home' , success: "The super potin was succesfully saved !"
    else
      render 'new' , danger: "Error : you need to complete this field "
      puts 'Gossip is invalid'

      end
  end

  def edit
     @gossip = Gossip.find(params[:id])
  end

  def update
     @gossip = Gossip.find(params[:id])
     gossip_params = params.require(:gossip).permit(:title, :content)
     @gossip.update(gossip_params)

      if @gossip.update(gossip_params)
      redirect_to @gossip

      else render :edit
      end
   end

   def destroy
   end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
      @gossip = Gossip.all
    end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def team
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/city/index.html.erb
<h1>Welcome to the page of The Gossip from this city !</h1>


<% @city.each do | city| %>

          <p>
            nom de la ville: **
            <%= city.name %>
            <%= %>
            **<br/>
            Le code postal : **
            <%= city.zip_code %>
            **<br/>
          </p>
          <button type="button" class="btn btn-pill btn-secondary">
            <a href="/gossip/<%=1 %>">Lien vers ce gossip</a>
          </button>


<% end %>

app/views/city/show.html.erb
<h1>City</h1>
<p>All Gossips from '
  <%= @city.name %>
  ' are here!</p>

<!-- DEBUT CARD HEARDER -->
<div class="row">
  <% @city.users.each do |user| %>
    <% user.gossips.each do |gossip| %>

      <div class="col-md-4">

        <div class="card-deck mb-3 text-center">

          <div class="card card-accent-dark mb-3" style="max-width: 20rem;">
            <div class="card-header">Author :
              <%= user.first_name %>
            </div>
            <div class="card-body">
              <p>
                Title: **
                <%= gossip.title %>
                <%= %>
                **<br/>
                Content : **
                <%= gossip.content %>
                **<br/>
              </p>

            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

</div>
<!-- FIN CARD HEADER -->

app/views/gossip/edit.html.erb
<h1>Edit a gossip</h1>


<%= form_for @gossip do |f| %>

<div class="form-group">
  <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.text_area :content, class: 'form-control' %>
</div>

<div class="form-group">
	<button>Edit gossip</button>
</div>

<% end %>

app/views/gossip/gossip.html.erb
<h1>Gossip</h1>
<p>Title : <%= @gossip.title %></p> 
<p>Author: <a href="/user/<%= @gossip.user_id %>"><%= @gossip.user.first_name %></a></p>
<p>Creation date: <%= @gossip.created_at%></p>
</br>
<p>Content: <%= @gossip.content %></p>

app/views/gossip/new.html.erb
<html>
  <body>
    <!-- ... -->
    <h1>Let's gossip ;-)<h1>

    <%= form_tag url_for(action: 'create'), method: "post" do %>

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title'%>
      <br /> <br />

      <%= label_tag 'Content' %>
      <%= text_area_tag 'content' %>
      <br /> <br />

      <%= submit_tag "Create Gossip" %>

    <% end %>
    <!-- debut alerte boostrap -->
    <% flash.each do |name, msg| %>
    <div class="alert alert-<% name %>">
      <% msg %>
    </div>
      <% end %>
      <!-- fin alerte boostrap -->

    <% if @gossip.errors.any? %>
      <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

  </body>
</html>

app/views/gossip/show.html.erb
<h1>Gossip</h1>
<p>Title : <%= @gossip.title %></p>
<p>Author: <a href="/user/<%= @gossip.user_id %>"><%= @gossip.user.first_name %></a></p>
<p>Creation date: <%= @gossip.created_at%></p>
</br>
<p>Content: <%= @gossip.content %></p>
</br>
<p>City of this author: <a href="/city/<%= @gossip.user.city_id %>"><%= @gossip.user.city.name %></a></p>

<a href="<%= edit_gossip_path(@gossip.id) %>" class="btn btn-secondary"> Edit gossip</a>

<a href="<%= gossip_path(@gossip.id) %>" class="btn btn-danger" data-confirm="For real bro ?"> Delete gossip</a>

app/views/user/show.html.erb
      <h1> Author : <%= @user.first_name %></h1><br>
      <b>Last name :</b><p><%= @user.last_name%></p>
      <b>Decription :</b><p><%= @user.description%></p>
      <b>Email :</b><p><%= @user.email %></p>
     <b>Age :</b><p><%= @user.age %></p>
     <b>City :</b><p><%= @user.city.name %></p>
     <b>Active gossips list :</b>
     <p> <% @user.gossips.each do |gossip| %>

      - "<%= gossip.content %>"<br>
      <% end %>
    </p>